### ISSUE TITLE
Google API FCM v1 available in google-api-client gem (starting 0.29.2)

### ISSUE THREAD

**Issue by oleksii-leonov** [oniksfly/google-api-fcm#14]
Thanks for the great work, this gem helps a lot!

Recently I found that official `google-api-client` gem added support for FCM v1 in version 0.29.2 (21 May 2019).

Docs and link to sources:
- https://googleapis.dev/ruby/google-api-client/latest/Google/Apis/FcmV1.html
- https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google/apis/fcm_v1.rb

It's very similar and switching between `google-api-fcm` and official `google-api-client` require to update only several lines of application code.

I believe, it could make sense to add a note about official `google-api-client` gem into Readme.

**Comment by oniksfly** [comment]
Thank you! Updated readme.
